name: Test

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

env:
  LLVM_VERSION: 15

jobs:
  test:
    name: test
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Test in Docker
      run: |
        docker container run -t --mount type=bind,src=$PWD,dst=/go/src/github.com/go-clang/clang-v${LLVM_VERSION} -w /go/src/github.com/go-clang/clang-v${LLVM_VERSION} ghcr.io/go-clang/base:${LLVM_VERSION} make test
